/*
 * character
 *
 * test swagger
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
)

func main() {
	log.Printf("Server started")

	router := mux.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
