/*
 * character
 *
 * test swagger
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CharacterBody struct {

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Email string `json:"email"`

	DateOfBirth string `json:"dateOfBirth"`
}
