/*
 * character
 *
 * test swagger
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CharacterCharacterIdBody struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`
	// If a new email is given, the character's email verified property will be set to false.
	Email string `json:"email,omitempty"`

	DateOfBirth string `json:"dateOfBirth,omitempty"`
}
