/*
 * character
 *
 * test swagger
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// character info
type Character struct {
	// Unique identifier for the given character.
	Id int32 `json:"id"`

	CharacterName string `json:"characterName,omitempty"`

	Hp int32 `json:"hp,omitempty"`

	Mp int32 `json:"mp,omitempty"`
	// The date that the character was created.
	CreateDate string `json:"createDate,omitempty"`
}
